# Site
repository: abdl-dev/abdl-dev.github.io
favicon: assets/icon.png

# Content configuration version
version: 2 # get rid of this later

# Personal Info
name: Abdul Malek
title: Software Engineer
email: me@abdl.dev
email_title: E-Mail
phone: (646) 552-1769
phone_title: Phone
location: New York, NY

# Dark Mode (true/false/never)
darkmode: true

# Social Links
github_username: abdl-dev
linkedin_username: abdl
resume_link: assets/resume.pdf

about_profile_image: assets/profile.jpg

content:
  - title: EDUCATION
    layout: list
    content:
      - layout: left
        title: Saint Louis University
        caption: 1 North Grand Boulevard, St. Louis, MO 63103
        description: |
            - Major: Computer Science
            - Minor: Mathematics

      - layout: left
        title: Hunter College
        caption: 695 Park Ave, New York, NY 10065

      - layout: left
        title: Stuyvesant High School
        caption: 345 Chambers St, New York, NY 10282


  - title: PROJECTS & WORK EXPERIENCE
    layout: list
    content:
      - layout: left
        title: DevOps at Intersection
        quote: >
          // Formerly, Control Group
        description: |
          Worked with DevOps team to build an internal python-based web application that interfaced
          with several AWS services to provide user-friendly, human-interpretable Zendesk tickets
          for company clients. Currently in production status.

      - layout: left
        title: Quadrocopter Development at Intersection
        quote: >
          // Formerly, Control Group
        description: |
          Worked with a small team with robotics experience to build and program an
          ArduPilot-controlled UAV incorporating GPS, magnetometer-based orientation, sonar-based
          speed control, and an accelerometer/gyroscope for feedback.

      - layout: left
        title: Programming & Security Competitions
        quote: >
          // ICPC, CSAW CTF, UFO CTF, & picoCTF
        description: |
          Competed in the International Collegiate Programming Contest (ICPC). Competed in several
          capture-the-flag (CTF) style hacking/security competitions. Competitively solved
          challenges involving binary exploitation, forensics, reverse engineering, script
          exploitation, and cryptography. Ranked 38th internationally in UFO CTF and 42nd nationally
          in picoCTF. (Team Qubit)

      - layout: left
        title: LWJGL Game Development
        description: |
          Developed 3D arcade game that interfaces with a server, with dynamic web content
          displaying animated score updates in real time, incorporating multiple graphics and web
          development tools/libraries.

      - layout: left
        title: NetLogo Game Development
        description: |
          Developed multiple fully featured ports of popular mobile games, rewritten in NetLogo.
          Games include Defender, a feature-complete port of a dynamic-difficulty wave defense game,
          Line Runner, and a variation of B-Shooter.

      - layout: left
        title: Stuy++
        description: |
          Started and led team with varying experience in development of new technology to modernize
          school. Developed networked monitoring system (wireless mesh) for unreliable escalators
          using Arduino and XBee.

      - layout: left
        title: Software Engineering at FIRST Robotics
        description: |
          Led team in developing software for multi-system robot. Won first place at New York City
          Regional, won Chairmanâ€™s Award at Connecticut Regional, and competed in the FIRST
          Championship. (FRC)

      - layout: left
        description: |
          **Miscellaneous:** Putnam Mathematical Competition, TEDxStuyvesantHS (Organizer)


  - title: TECHNICAL SKILLS
    layout: text
    content: |
        **Languages:** Python, C, C++, Java, JavaScript, Haskell, Go, x86, Lisp/Scheme\
        **Skills:** Linux, Git, Vim, AWS, SQL, Node.js, Flask, OpenGL, LWJGL, Arduino\
        **Experience:** distributed systems, operating systems, dynamic programming, natural
        language processing, security, cryptography, compilers, graphics, web, various math

# Footer
# footer_show_references: false
references_title: Wat (Override references text)

plugins:
 - jekyll-seo-tag

 # TODO
 # - Change all double quotes to single quotes
 # - Strip all unused variables from files
 # - Make all the site content indentations line up
 # - Fix header alignment
 # - fix h3 being small
 # - Get everything to work with bootstrap 5.0 (particularly 3.4 -> 4.0 changes)
 # - Add favicon.ico
